package constants

const (
	OUTBOUND_ORDER_STATUS_PICKLISTED int64 = iota + 1 // get from table wms_status
	OUTBOUND_ORDER_STATUS_CANCELED
	OUTBOUND_ORDER_STATUS_PENDING
	OUTBOUND_ORDER_STATUS_PICKED
	OUTBOUND_ORDER_STATUS_PACKED
	OUTBOUND_ORDER_STATUS_SHIPPED
	OUTBOUND_ORDER_STATUS_DELIVERY
	OUTBOUND_ORDER_STATUS_DELIVERED
	OUTBOUND_ORDER_STATUS_RETURNED
	OUTBOUND_ORDER_STATUS_COMPLETE_REPUSH
)

const (
	OUTBOUND_ORDER_TYPE_RECEIPT           string = "RECEIPT"
	OUTBOUND_ORDER_TYPE_ORDER             string = "ORDER"
	OUTBOUND_ORDER_TYPE_INTERNAL_TRANSFER string = "INTERNAL_TRANSFER"
	OUTBOUND_ORDER_TYPE_ADJUSTMENT        string = "ADJUSTMENT"
	OUTBOUND_ORDER_TYPE_VENDOR_RETURN     string = "VENDOR_RETURN"
)

const (
	OUTBOUND_ORDER_CONFIG_DESIGNATE_DATE = 2097152
)
