package constants

var MAP_EMOJI_WAREHOUSE = map[string]int64{
	EMOJI_NUMBER_ONE: 14,
	EMOJI_NUMBER_TWO: 540,
}

const (
	WAREHOUSE_CONFIG_ENABLE_LOCATION                   = 1
	WAREHOUSE_CONFIG_ALLOW_RECEIVE_SSCT                = 2
	WAREHOUSE_CONFIG_FAST_EXPORT_IT_OUT                = 8
	WAREHOUSE_CONFIG_FAST_RECEIVE_IT_OUT               = 16
	WAREHOUSE_CONFIG_FAST_RECEIVE_IT_IN                = 32
	WAREHOUSE_CONFIG_ALLOW_RECEIVED_TRANSFER_WAREHOUSE = 64
	WAREHOUSE_CONFIG_ALLOW_AUTO_EXPORT_TESTER          = 128
	WAREHOUSE_CONFIG_ALLOW_LOCATION_SCHEDULE           = 256
	WAREHOUSE_CONFIG_NOT_ALLOW_PRINT_PACKED_LABEL_WEB  = 512
	WAREHOUSE_CONFIG_FAST_EXPORT_IT_IN                 = 1024
	WAREHOUSE_CONFIG_ALLOW_RFID                        = 2048
	WAREHOUSE_CONFIG_HAS_CONVEYOR_BELT                 = 8192
)
