DiscordBot:
    butler:
        Token: MTEzMzgxMDY3MjM5MjczNjg1MA.GmvkNH.ywqEVKjPEs5I3RQOQizc04rwf19dFbaa3PvYX4

Mysql:
    Host: localhost
    Port: 3306
    DBName: db_docker_local
    Username: root
    Password: linhnl

Makersuite:
    ApiKey: AIzaSyAj8DC0foFWGNzfc-2acLBO7Wm-um00yKI
    Model: gemini-1.0-pro-latest